// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xllhftvuxflgdwcfsvue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsbGhmdHZ1eGZsZ2R3Y2ZzdnVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTA5NTYsImV4cCI6MjA2NjAyNjk1Nn0.h1LTMh02LWfYVzgh0Icq3F2Lw5fbemD-LTV2xDZewDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);